# Generated by Django 4.2 on 2023-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('adresse', models.CharField(blank=True, max_length=128, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=128, null=True)),
                ('variant', models.CharField(choices=[('NLH', 'NLH'), ('PLO-4', 'PLO-4')], max_length=128)),
                ('limit', models.CharField(choices=[('1€-2€', '1€-2€'), ('2€-4€', '2€-4€'), ('5€-5€', '5€-5€'), ('5€-10€', '5€-10€'), ('10€-20€', '10€-20€'), ('20€-40€', '20€-40€')], max_length=128)),
                ('description', models.TextField(blank=True, max_length=2048)),
            ],
        ),
    ]
