# Generated by Django 4.2 on 2023-06-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etablissement',
            new_name='ParisEtablissement',
        ),
    ]
