# Generated by Django 4.2 on 2023-06-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0002_rename_etablissement_parisetablissement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parisetablissement',
            options={'verbose_name_plural': 'Liste des Clubs'},
        ),
    ]
