# Generated by Django 4.2 on 2023-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provinceetablissement',
            options={'verbose_name_plural': 'Liste des Casinos'},
        ),
        migrations.AddField(
            model_name='provinceetablissement',
            name='province',
            field=models.CharField(choices=[('NW', 'NW'), ('NE', 'NE'), ('SW', 'SW'), ('SE', 'SE')], default='NW', max_length=128),
            preserve_default=False,
        ),
    ]
