# Generated by Django 4.2 on 2023-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_alter_provinceetablissement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceetablissement',
            name='province',
            field=models.CharField(choices=[('NW', 'Nort West'), ('NE', 'North East'), ('SW', 'South West'), ('SE', 'South East')], max_length=128),
        ),
        migrations.AlterField(
            model_name='provinceetablissement',
            name='variant',
            field=models.CharField(choices=[('NLH', 'NLH'), ('PLO-4', 'PLO-4'), ('NLH , PLO-4', 'NLH , PLO-4')], max_length=128),
        ),
    ]
